---
title: 'The Citation File Format (CFF)'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is the Citation File Format (CFF)?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Learn what the Citation File Format is, and what problems it solves.

::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction to the Citation File Format


The [Citation File Format (CFF)](https://citation-file-format.github.io/) is a format for files that contain citation metadata for software.
It has been developed to make it easier for software authors to provide the complete and correct set of citation metadata for their software projects.

CFF files are called `CITATION.cff`.
They are meant to live together with the source code of the software, usually in a source code repository.
`CITATION.cff` files can also be shipped together with the software, for example when software is distributed in downloadable archives.

One of the main aims of CFF is to make these metadata files accessible for both humans and machines.
To achieve this, CFF files are written in a data serialization markup language called YAML.
YAML is often used for software configuration files, and therefore there is a chance that software developers already know it.

The contents of a simple CFF file are shown below, but CFF can do more than this, which you will learn about in the following sections.

```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/1234-5678-9101-1121
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2021-08-11
```

## Very brief introduction to YAML

One of the features of YAML is that it uses very few actual markup symbols.
This makes it easier to read than languages that make extensive use of brackets to structure data, such as JSON.

YAML uses so called "block collections", where each entry begins on its own line, and the scope is defined using indentation.

For data structures, YAML most importantly defines collections:

- *mappings*, where data is provided as key-value pairs such as `foo: bar`, and
- *sequences*, where each entry starts with a dash and a whitespace, followed by the data value, as in `- Entry 1`.

Mappings and sequences can be mixed as well.
This means that you can map keys to sequences, as in the following example. We could call those "named lists".

```yaml
colors:
  - green
  - white
  - orange
  - blue
```

You can also have sequences of mappings, as in the following example, where we could call each entry an "anonymous object".

```yaml
-
  age: 23
  name: Kim
-
  age: 42
  name: Alex
```

Values in YAML have different data types, similar to programming languages.

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor

In the YAML specification, this is worded less intuitively:

> A YAML node represents a single native data structure. Such nodes have content of one of three kinds: scalar, sequence or mapping. 
> In addition, each node has a tag which serves to restrict the set of possible values the content can have.

This episode uses "mappings" and "sequences", but not "scalars".
Should learners ask about this, either refer them to the [YAML specifications](https://yaml.org/spec/) themselves,
or give them the definition of "scalar", which for YAML 1.2.2 is:

> The content of a scalar node is an opaque datum that can be presented as a series of zero or more Unicode characters.

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

## YAML in the Citation File Format

The Citation File Format uses both mappings and sequences, and mainly three data types:

- **strings**, written in YAML as `"string value"` (optionally without the double quotes, if the string contains no special characters)
- **numbers** - either integers or floats - written in YAML without quotes as `42` or `0.42`
- **integers**, written in YAML without quotes as `42`

The Citation File Format project also provides a 
[*schema* (as JSON Schema)](https://github.com/citation-file-format/citation-file-format/blob/main/schema.json) 
that can be used to check the validity of `CITATION.cff` files.
The schema defines what keys are required, and what values are valid for which keys.
Amongst other things, the schema defines *enums* (enumerated types) and *regular expressions* for definitions.

::::::::::::::::::::::: callout

## Citation File Format schema guide

The [Guide to the Citation File Format schema](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md)
provides detailed information for each key and what values it can take.
It is the definitive source of information regarding the Citation File Format.

::::::::::::::::::::::::::::::::

## Required keys

`CITATION.cff` files must contain at least the following four key-value pairs:

- **`cff-version`** followed by the version string for a published version of the Citation File Format itself.  
This key tells the user what keys and values the file should contain based on the respective schema, and to identify the file as a CFF file, together with the file name.
- **`message`** followed by a message to human readers, to tell them what the file represents.  
This key tells the user what they are looking at, and to help them make proper use of the file data.
- **`title`** followed by the name of the software.  
This key tells the user what name the software should be cited under. This is the equivalent of the title of a paper.
- **`authors`** followed by a sequence of at least one software author.  
This key tells the user who should be cited as authors of the software.

A minimal valid `CITATION.cff` file could look like this:

```yaml
cff-version: "1.2.0"
message: "If you use this software, cite it using these metadata."
title: "Astronaut Analysis"
authors:
  - family-names: "Druskat"
    given-names: "Stephan"
  - name: "The Astronaut Analysis Team"
```

Note that there are two types of authors in the example: 

- **person authors** have at least one or more given names (e.g. "first names" in some cultures) and one or more "family names".
The Citation File Format aims to implement a culturally neutral model for personal names, 
but formalizing names in a machine-readable schema is hard.
You can read about how name keys are intended to be used in the [CFF schema guide for persons](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsperson).
- **entity authors** represent groups of people or institutions or similar that can act as software authors.
Entity authors can be used as a sensible fallback mechanism for cases where the real authors cannot be determined.
We have seen this in the first attempt to create a citation for Astronaut Analysis, where the single author was "The Astronaut Analysis developers".

## What the Citation File Format can do

CFF has been developed with the software citation principles in mind.
It provides all the keys you need to provide citation metadata for your software in a way that fulfills the principles.

The following example shows a more typical CFF file that provides all the necessary information 
to adhere to the software citation principles.

```yaml
cff-version: "1.2.0"
message: "If you use this software, please cite it using these metadata."
title: "My Research Software"
abstract: "This is my awesome research software. It does many things."
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: "https://orcid.org/1234-5678-9101-1121"
  - name: "The Research Software project"
version: "0.11.2"
date-released: "2021-07-18"
identifiers:
  - description: "This is the collection of archived snapshots of all versions of My Research Software"
    type: "doi"
    value: "10.5281/zenodo.123456"
  - description: "This is the archived snapshot of version 0.11.2 of My Research Software"
    type: "doi"
    value: "10.5281/zenodo.123457"
license: "Apache-2.0"
repository-code: "https://github.com/citation-file-format/my-research-software"
```

Remember the minimal metadata that software authors should provide to make the software properly citable?

- A list of the software authors,
- the name of the software,
- the version of the software,
- a method to access the software version to be cited, ideally through a persistent unique identifier such as a DOI.

The example above includes all this information, and more. The `abstract` key gives a brief summary of what the software does.
The `license` key tells us something about the conditions the software can be used under. 
The `date-released` field gives us a date that we can use in our citation.
The `repository-code` field gives us a link to the place where the software has been (and perhaps still is) developed.
And we also get some more information about the first listed author.

There is more: with CFF you can, for example, provide a list of references for your software under the `references` key.
You can also ask people to cite something else (for example a paper) in addition to citing the software itself, by providing
a citation under the `preferred-citation` key.

CFF defines more keys than the ones above, but don't worry, you will not need to learn keys by heart.

## Creating a `CITATION.cff` file

1. Log in to GitHub with your personal account
2. Fork the repository at https://github.com/sdruskat/astronaut-analysis by clicking the "Fork" button on the repository page
3. (Optional) Choose the fork target account or organization
4. Create a `CITATION.cff` file for your forked repository:

- You don't have to do this manually. You can use *cffinit*: https://bit.ly/cffinit
- In a new browser tab, start to create a file called `CITATION.cff` from the GitHub UI in the repository root
- Copy and paste the final file you have created with cffinit into the editor window in github
- Commit the file
- What are the change in the GitHub UI?

- Users can read the file
- Users have the widget

- Challenge: What is missing for a citation based on the software citation principles?

:::: instructor

DOI!

::::::::::::::

::::::::::::::::::::::::::::::::::::: keypoints 

- The Citation File Format (CFF) is a human- and machine-readable file format for software citation metadata.
- Valid CFF files are called `CITATION.cff` and contain YAML data.
- The CFF *schema* defines what keys and values a CFF file can and must have.
- CFF can provide comprehensive citation metadata for a software (version).
- CFF can provide the references for a software, e.g., its dependencies.
- CFF can provide metadata for another output that should be cited in addition to the software itself.

::::::::::::::::::::::::::::::::::::::::::::::::

